### ISSUE TITLE
Readme missing

### ISSUE THREAD

**Issue by dspace-projects** [REMEXLabs/openape.js#1]

**Comment by Lukas84** [comment]
Done, but I could not find openape.js in the DSpace any more.

 

Von: GPII Developer Space [mailto:notifications@github.com] 
Gesendet: Sonntag, 4. März 2018 14:24
An: REMEXLabs/openape.js <openape.js@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [REMEXLabs/openape.js] Readme missing (#1)
